### PR TITLE
Instant Paypal Notification Route

### PR DESCRIPTION
**Pull request by theunknownartisthour**
Figured this'd be handy...
~Needs a bit of adjustment for NodeBB~

### CODE REVIEW

**Comment by psychobunny** [comment]
...

Woah.

**Comment by psychobunny** [comment]
Accepting this PR without testing because

A) what do I test 
B) you're awesome

**Comment by psychobunny** [comment]
Do I just make skeleton plugins from now on and you do the rest? :p

<3

**Comment by theunknownartisthour** [comment]
:) if you gave me an overview...I mean...yeah hahahhaa.

What this route should do\* if properly setup with a paypal account is display little alerts on the backend. That's basically it...
[https://developer.paypal.com/webapps/developer/docs/classic/products/instant-payment-notification/](https://developer.paypal.com/webapps/developer/docs/classic/products/instant-payment-notification/)

What'd really be cool and a bit overboard (I'd have fun with this) would be to add the sort of dashboard statistics that are on the backend. When someone pings the route there's the date and time, and there's feedback for example when a transaction does not go through or fails, so there's a potential to do positive and negative counts.

**Pull request merged**
